# creating this file just to allow the serverless framework pro to register our repo
# for CI/CD
org: jetpax # Enter your tenant name here
app: workshop # Enter your application name here
service: fullstack-website

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2