# creating this file just to allow the serverless framework pro to register our repo
# for CI/CD
org: jetpax # Enter your tenant name here
app: workshop # Enter your application name here
service: fullstack-root-filler

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

functions:
  testEndpoint:
    handler: handler.testEndpoint
    events:
      - schedule: rate(5 minutes)
