org: jetpax # Enter your tenant name here
app: workshop # Enter your application name here
service: fullstack-restapi # update

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  environment:
    database_submissions_name: ${param:jpx-workshop-ddbtable-name}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: ${param:jpx-workshop-ddbtable-arn}

functions:
  formSubmit:
    handler: index.submit
    timeout: 10
    events:
      - http:
          path: submit
          method: post
          cors: true

